### ISSUE TITLE
Controller Rumble Not Working on Ubuntu

### ISSUE THREAD

**Issue by SleepySpaceDad** [NoelFB/Celeste#21]
I play the game on both Ubuntu and Windows with an X-Box One controller. On Windows, I get a controller rumble whenever I dash. On Ubuntu 18.04.1, my controller never rumbles. I'm running kernel 4.15 currently.

**Comment by egordorichev** [comment]
I think this is some MonoGame related Linux issue. Doesn't seem to work with some other MonoGame things too, but works just fine with every other engine.

**Comment by 0x0ade** [comment]
Celeste only uses MonoGame for the console ports.
