### ISSUE TITLE
Article on the physics system has moved

### ISSUE THREAD

**Issue by kawa-yoiko** [NoelFB/Celeste#27]
Matt's article has been updated and moved to [Medium](https://medium.com/@MattThorson/celeste-and-towerfall-physics-d24bd2ae0fc5), and the original link has been invalidated. It would be nice to update `Source/Player/Readme.md` to point there instead.

It is a very inspiring design. I modelled a platformer game after this and it's been a delightful experience. Thank you.

**Comment by NoelFB** [comment]
Thanks, fixed!
