### ISSUE TITLE
Softlocks with aim assist

### ISSUE THREAD

**Issue by vXtreniusX** [NoelFB/Celeste#31]
Issue: The game softlocks in certain cutscenes where the character dashes, such as credits, when using aim assist.
How to replicate: 

1. In a save file, turn on assist mode
2. in a level, pause.
3. go to assist options
4. enable aim assist
5. enter one of those cutscenes

Possible fix: Ignore/turn off aim assist in those cutscenes and enable it after cutscene ends. Or adding additional input to the demo, when assist is on.

Video with the issue: [https://youtu.be/2fhDyXxoZcc](https://youtu.be/2fhDyXxoZcc)

**Comment by NoelFB** [comment]
Thanks, should be fixed in the beta. Will be in the main version soon.
