### ISSUE TITLE
EGS Marked as 64 bits only

### ISSUE THREAD

**Issue by Fancy2209** [NoelFB/Celeste#32]
The Epic Games Store version is marked as 64 bits only even tough the game is 32 bit app
![image](https://user-images.githubusercontent.com/64917206/112770355-f25fa700-9015-11eb-991e-12f016c76236.png)

**Comment by NoelFB** [comment]
We'll look into this shortly, thanks.

**Comment by NoelFB** [comment]
Just to clarify, are you on MacOS or Windows?
It looks like we already have a Windows 32 bit version but perhaps it's not accessible for some reason.

**Comment by NoelFB** [comment]
Nevermind, it should now be fixed.

**Comment by Fancy2209** [comment]
Just to say it was windows 
And it works now
