### ISSUE TITLE
Missing File slot

### ISSUE THREAD

**Issue by NoelFB** [NoelFB/Celeste#4]
On rare occasions, the UI for the file slot will not display / ease into the screen

![20180303025341_1](https://user-images.githubusercontent.com/269893/36928524-60a81756-1e3b-11e8-998b-84a93ae459cb.jpg)

**Comment by robhshu** [comment]
@NoelFB 

I'm missing the third slot after my issue #12 

PC (Stream) v1.2.3.1

![2018-05-22 13_06_59-steam](https://user-images.githubusercontent.com/1644232/40361445-449a6940-5dc1-11e8-857f-d571e8d2fe05.png)

**Comment by robhshu** [comment]
The third slot is selectable, but then soft-locks the game.

I've attached a video showing me entering the menu:

[Celeste 5_22_2018 1_09_26 PM.zip](https://github.com/NoelFB/Celeste/files/2026503/Celeste.5_22_2018.1_09_26.PM.zip)

**Comment by robhshu** [comment]
I fixed this by reinstalling the game. The cloud saves were not corrupted (even after the extra deaths) and no data was lost!

**Comment by NoelFB** [comment]
Fixed, will be in our next patch.
