### ISSUE TITLE
What the function Calc.Approach(x, y, z) do?

### ISSUE THREAD

**Issue by Perh0nen** [NoelFB/Celeste#42]
![image](https://user-images.githubusercontent.com/121351346/210950341-8c1b42fc-68e3-4361-96ae-a0273baec4ca.png)
It's been used in many places. Wonder what's the specific meaning it return?

**Comment by NoelFB** [comment]
It makes X approach Y by a delta of Z, but doesn't overstep it.
```
float x = 10, y = 23, z = 5;
x = Calc.Approach(x, y, z); // x = 15 now
x = Calc.Approach(x, y, z); // x = 20 now
x = Calc.Approach(x, y, z); // x = 23 now
```
