### ISSUE TITLE
Some Chinese translation problems

### ISSUE THREAD

**Issue by DemoJameson** [NoelFB/Celeste#9]
I found some errors in `Content\Dialog\Simplified Chinese.txt:`
1. Line 70 OPTIONS_SPEEDRUN_CHAPTER=**第章** -> **章节**
2. Line 143 ASSIST_SKIP=	辅助{n}跳**跃** -> **关**
3. Line 2309 你看到了我内心深处的事**务**，{n}这让我觉得很尴尬。**务** -> **物**
4. Line 3487 **既是**你跑回你的车上，驾车回家{n}也没什么好害臊的。**既是** -> **即使**
5. If Alex is Theo's elder sister then all **姐妹** and **妹妹** need to be changed to **姐姐**, otherwise all **姐妹** and **姐姐** need to be changed to **妹妹**. 

One suggestion for improvement is to translate dash into **冲刺** instead of **突进**.

**Comment by NoelFB** [comment]
Thanks for the feedback, I've had this verified and a future update will have these in them!

**Comment by DemoJameson** [comment]
I have modified the issue and added an error. You may not notice it.

- Line 143 ASSIST_SKIP=	辅助 {n} 跳**跃** -> **关**

- And I think **Assist Mode** should be translated as **辅助模式**，so all **帮助模式** should be changed to **辅助模式**.  **帮助模式** is more like a translation from **Help Mode**. 
This can also be unified with the translation of **ASSIST_SKIP** mentioned above.
